version: "3.9"

services:
  devopsdb:
    image: lathadevopsprof/automation:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    network:
      - mynetwork

  application:
    image: lathadevopsprof/automation:appimage
    ports:
      - "1235:8080"
    deploy:
      replicas: 3
    network:
      - mynetwork
    depends_on:
      - devopsdb
network:
   mynetwork:
      driver: overlay

