version: "3.9"

services:
  devopsdb:
    image: lathadevopsprof/automation:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  application:
    image: lathadevopsprof/automation:appimage
    ports:
      - "1235:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
